version: '3'
services:
  app-db:
    image: "mariadb:11.4.2"
    container_name: app-db
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  app-api:
    image: "app-api"
    container_name: app-api
    build: ./api
    ports:
      - 5000:5000
    env_file:
      - .env
  app-web:
    image: "app-web"
    container_name: app-web
    build: ./web
    environment:
      - API_URL={API_URL}
    ports:
      - 8080:8080

volumes:
  data: